### ISSUE TITLE
Deserialization issue for FastapiActuatorServer

### ISSUE THREAD

**Issue by hexfati** [stefanodellosa-personal/WADAS#41]
Error generated importing a YAML file having no ActuatorServer configured.
Probably it needs a check on `wadas_config["actuator_server"]` before invoking `FastAPIActuatorServer.actuator_server = FastAPIActuatorServer.deserialize(
                    wadas_config["actuator_server"]
                )`

Traceback:
`Traceback (most recent call last):
  File "C:\Users\Netgroup\PycharmProjects\WADAS\src\domain\mainwindow.py", line 532, in load_config_from_file
    FastAPIActuatorServer.actuator_server = FastAPIActuatorServer.deserialize(
  File "C:\Users\Netgroup\PycharmProjects\WADAS\src\domain\fastapi_actuator_server.py", line 60, in deserialize
    return FastAPIActuatorServer(**data)
TypeError: domain.fastapi_actuator_server.FastAPIActuatorServer() argument after ** must be a mapping, not str`

**Comment by stefanodellosa-personal** [comment]
Is gonna be solved in my next push
