### ISSUE TITLE
FTP Server does not work after changing operating mode

### ISSUE THREAD

**Issue by hexfati** [stefanodellosa-personal/WADAS#44]
Steps to reproduce:

1. Start WADAS and configure an FTP camera and the FTP server (without running the test).
2. Click OK.
3. Select the "animal detection and classification mode."
4. Run detection.
5. Connect with FileZilla and upload the image; the processing should be successful.
6. Click on Stop detection.
7. Change the mode to "animal detection mode."
8. Run detection.
9. Now, if you try to connect with FileZilla using the same credentials specified earlier, you should encounter issues (it either fails to authenticate or the server does not accept the connection).

**Comment by hexfati** [comment]
Same issue if you:
1. load a config file
2. add a new FTP camera
3. select "animal detection mode"/"animal detection and classification mode"
4. run detection
5. try to connect with Filezilla you should encounter "530 Auth failed"

**Comment by cdimauro** [comment]
It'd be better to "convert" those issues to proper test cases, to catch them in future code changes.
